name: ibox
version: 1.0.1
description: >-
  A Dart Command Box for Developer.Helper you use `npm`,`pub` and so on...
homepage: https://github.com/Pluckypan/iBox
documentation: https://github.com/Pluckypan/iBox
repository: https://github.com/Pluckypan/iBox
authors:
  - Plucky <plucky@echo.engineer>

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  args: ^1.5.2
  dart_inquirer: ^1.0.0
  io: ^0.3.2+1
  yaml: ^2.2.0
  path: ^1.6.4

dev_dependencies:


executables:
  ibox: main