name: ibox
version: 0.0.3
description: A Dart Command Box for Developer.
homepage: http://1991th.com
documentation: https://github.com/Pluckypan/iBox
repository: https://github.com/Pluckypan/iBox
authors:
  - Plucky <plucky@echo.engineer>

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  args: ^1.5.2
  dart_inquirer: ^1.0.0
  yaml: ^2.2.0
  path: ^1.6.4

dev_dependencies:


executables:
  ibox: main