name: ibox
version: 1.0.0
description: >-
  一个 Dart 实现的终端指令盒子，简化一些常用指令，方便日常开发。A Dart Command Box for Developer.
homepage: https://github.com/Pluckypan/iBox
documentation: https://github.com/Pluckypan/iBox
repository: https://github.com/Pluckypan/iBox
authors:
  - Plucky <plucky@echo.engineer>

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  args: ^1.5.2
  dart_inquirer: ^1.0.0
  io: ^0.3.2+1
  yaml: ^2.2.0
  path: ^1.6.4

dev_dependencies:


executables:
  ibox: main